adversary_weight: 10.0
batch_size: 512
cr_training_file: https://cernbox.cern.ch/remote.php/dav/public-files/r0GQeSVMuu0mDKX/processed_output_controlRegion_corrected.pkl
dropout_array: 0.2
epochs: 100
filters_cnn_MSeg:
- 32
- 16
- 8
filters_cnn_constit:
- 64
- 32
- 32
- 16
filters_cnn_track:
- 64
- 32
- 32
- 16
frac_list: 0.5
hidden_layer_fraction: 1.0
include_high_mass: true
include_low_mass: true
layers_list: 1
lr_values: 0.0008
mH_parametrization: false
mS_parametrization: false
main_training_file: https://cernbox.cern.ch/remote.php/dav/public-files/32dqr9gSbmQdj3W/processed_output_Lxy1500_Lz3000_3_slim05.pkl
model_name: default
nodes_MSeg_lstm: 5
nodes_constit_lstm: 10
nodes_track_lstm: 10
num_splits: 50
reg_values: 1.0e-11
